### ISSUE TITLE
[vite] Internal server error: Identifier 'AppExport' has already been declared

### ISSUE THREAD

**Issue by GOWxx** [Code-Forge-Net/Remix-Dev-Tools#104]
I provided a minimal reproduction:
https://github.com/GOWxx/resolve-remx-vite-remix-dev-tools-problems

I did two things in this reproduction:

1. init a remix-vite project.
```bash
pnpm dlx create-remix@latest --template remix-run/remix/templates/vite
```
2. add remix-dev-tools follow the `readme` doc.

Run this project and access it in the browser, then you can see the error message.

**Comment by GOWxx** [comment]
link #99 

I noticed this [comment](https://github.com/Code-Forge-Net/Remix-Dev-Tools/issues/99#issuecomment-1943256284), but I have already added the plugin and still encountered an error. I'm not sure where the problem is.

**Comment by AlemTuzlak** [comment]
@GOWxx when using it with Vite you should ONLY add the plugin

**Comment by GOWxx** [comment]
> @GOWxx when using it with Vite you should ONLY add the plugin在使用Vite时，你应该只添加这个插件

OHHHHHHHH! I got it and it worked! thank you!

This experience is amazing. ^ ^

**Comment by AlemTuzlak** [comment]
Thank you for using it! Happy coding!
