### ISSUE TITLE
[vite] Internal server error: Identifier 'links' has already been declared

### ISSUE THREAD

**Issue by jgentes** [Code-Forge-Net/Remix-Dev-Tools#106]
If I run `remix vite:dev` without remixDevTools, it works fine. After adding `remixDevTools()` to my `vite.config.ts` and run `remix vite:dev` I get: `[vite] Internal server error: Identifier 'links' has already been declared`
![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/1149470/3672c0d6-f8ec-4788-a160-d67bcbd241a4)

The one oddity is that I'm using `remix-island` to create the header:
```ts
// remix-island is needed to address React 18.2 hydration issues
export const Head = createHead(() => (
  <>
    <Meta />
    <Links />
  </>
))
```
So maybe that has something to do with it?

This is remix 2.8

**Comment by AlemTuzlak** [comment]
Can you post your root.tsx?

**Comment by jgentes** [comment]
Sure: https://github.com/jgentes/mixpoint/blob/main/app/root.tsx

**Comment by AlemTuzlak** [comment]
@jgentes I think the issue is that you're exporting links and default at the bottom, try doing `export const links` and `export default function App` and I think it should work?

**Comment by jgentes** [comment]
That did it, thanks!
