### ISSUE TITLE
Migration guide misses start app with plugin

### ISSUE THREAD

**Issue by vandriesh** [Code-Forge-Net/Remix-Dev-Tools#110]
3.x docs:

https://github.com/Code-Forge-Net/Remix-Dev-Tools/tree/v3.7.4?tab=readme-ov-file#cjs-remix-server-setup-remix-run-server-started-by-remix-dev

```diff
- "dev": "remix dev -c \"npm run dev:serve\"",
+ "old_dev": "remix dev -c \"npm run dev:serve\"",
+ "dev": "remix dev -c \"rdt-serve ./build/index.js\" --manual",
```

would've been nice to have it mentioned in the migration section - could saved few minutes ;-)

nonetheless , terrific job here

**Comment by AlemTuzlak** [comment]
Thank you, I forgot this part in the readme, will update.

**Comment by AlemTuzlak** [comment]
added it
