### ISSUE TITLE
after upgrade I see no remix devtool icon toggler

### ISSUE THREAD

**Issue by vandriesh** [Code-Forge-Net/Remix-Dev-Tools#111]
and the manual mentions only vite mods, and remove v3 css modes from codebase. I assumed rdt vite plugin would do that for men (inject css)

but nothing (except my app) is on screen.

even terminal's output is not "modified" like in v3

**Comment by AlemTuzlak** [comment]
That shouldn't be the case 🤔 so you're saying you cant see the dev tools at all?

**Comment by AlemTuzlak** [comment]
@vandriesh mind creating a minimum repro for this?

**Comment by AlemTuzlak** [comment]
please re-open if you can muster a minimum repro!
