### ISSUE TITLE
plugin not showing up

### ISSUE THREAD

**Issue by cayblood** [Code-Forge-Net/Remix-Dev-Tools#117]
I just set up a brand new remix app with remix dev tools and tried adding the tailwind-palette plugin, but it doesn't seem to be showing up. My vite config looks like this:

```
import {
  vitePlugin as remix,
  cloudflareDevProxyVitePlugin as remixCloudflareDevProxy,
} from "@remix-run/dev";
import { defineConfig } from "vite";
import { remixDevTools } from "remix-development-tools";
import tsconfigPaths from "vite-tsconfig-paths";

export default defineConfig({
  plugins: [
    remixDevTools({
      pluginDir: "./plugins",
    }),
    remixCloudflareDevProxy(),
    remix(),
    tsconfigPaths(),
  ],
  server: {
    open: true,
  },
});
```

I've restarted the server, but I still don't see the icon.

**Comment by AlemTuzlak** [comment]
@cayblood due to some issues with the migration to v4 I had to disable plugins for now, hopefully I'll have them back in v4.1

**Comment by cayblood** [comment]
Thanks! I've never been responded to more quickly on a project than yours. You're a machine. Thanks for all your efforts, but also make sure you get some rest 😅.

**Comment by AlemTuzlak** [comment]
@cayblood depends on if you catch me at my pc or not, sometimes I miss a notification and it takes me a few weeks! 😆 
Thank you for the kind words! Hopefully I'll have it resolved soon.

**Comment by AlemTuzlak** [comment]
@cayblood upgrade to v4.1 and you should see them again!
