### ISSUE TITLE
Hydration Error... React 18 issue?

### ISSUE THREAD

**Issue by Pickra** [Code-Forge-Net/Remix-Dev-Tools#40]
## WHAT?!?@?!#?!
I followed the docs to [upgrade to remix-development-tools": "2.0.0"](https://github.com/Code-Forge-Net/Remix-Dev-Tools#getting-started).
I'm getting errors after upgrading. 

<img width="789" alt="Screenshot 2023-08-05 at 2 13 07 PM" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/5226549/28929030-5f76-4385-a55e-37aceb2322fc">

### `Hydration failed because the initial UI does not match what was rendered on the server` seems to be the most relevant error...
- https://github.com/remix-run/remix/discussions/5568
- https://github.com/remix-run/remix/issues/2947
- https://github.com/remix-run/remix/issues/1077#issuecomment-1117457264

## Versions
"@remix-run/node": "^1.14.3",
"@remix-run/react": "^1.14.1",
"@remix-run/dev": "^1.12.0",
"remix-development-tools": "2.0.0",
node: 18.16.1
npm: 9.5.1

## Action Items
- The consumer uses [remix-island](remix-island); see [remix-hydration-fix](https://github.com/kiliman/remix-hydration-fix); Maybe, I haven't looked into it...
- Add docs about using react v17 or `remix-island` with Remix-Dev-Tools? Likely...
- I'm wrong and there's something obvious I need to do? Also likely...
- Fix on your end? Unlikely, but you know better then me.

**Comment by AlemTuzlak** [comment]
@Pickra did you wrap your server context with initServer? And your fe with initClient? So in order for route boundaries to work it requires to hook into default exports in route files and add some additional divs, this then requires you to add the div on server and client to prevent issues. One thing that is a red flag for me is 1.14.1 of remix-run/react. The package uses a hook only available from 1.15 so you should upgrade it. And to be frank I haven't tried r17 versions at all, but the error you get is usually cuz you didn't do the initServer part

**Comment by Pickra** [comment]
My bad @AlemTuzlak , user error. All `@remix-run` deps are on `^1.19.1`. i borked the conditionals surrounding hydrate, in `entry.client.tsx`... Your biz is tight. Thanks for being so cool.
🌈🌈🦄🦄

**Comment by AlemTuzlak** [comment]
Glad to hear it! Code on!
