### ISSUE TITLE
TS import error on VSCode

### ISSUE THREAD

**Issue by keul** [Code-Forge-Net/Remix-Dev-Tools#48]
While the extension is working properly, VSCode is complaining about missing support for dynamic import.

```
Dynamic imports are only supported when the '--module' flag is set to 'es2020', 'es2022', 'esnext', 'commonjs', 'amd', 'system', 'umd', 'node16', or 'nodenext'.ts(1323)
```

I don't know is this is related to the remix v1/v2 state, but I'm wondering if the README can provide better help on how to properly fix this error.

**Comment by AlemTuzlak** [comment]
@keul This is an issue that pops up if you don't have a module specificed in your tsconfig. I've added a readme section that covers the issue!
