### ISSUE TITLE
The cjs file is incorrectly named in the package.json

### ISSUE THREAD

**Issue by Kilian** [Code-Forge-Net/Remix-Dev-Tools#5]
The dist folder contains an `index.cjs`, but your package.json says to look for an `index.umd.cjs`. Because of this Remix can't find the extension (probably the cause of https://github.com/Code-Forge-Net/Remix-Dev-Tools/issues/4 too)

![Selection_1864](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/41970/12220ce9-0cf4-408b-8085-dee67f9a69fe)

**Comment by Kilian** [comment]
To confirm: editing the main and require exports in package.json makes everything work swimmingly.

**Comment by AlemTuzlak** [comment]
@Kilian Omg you are right! Thank you, I just pushed a new release, it should be working now!
