### ISSUE TITLE
Error: Dynamic require of "remix-development-tools" is not supported

### ISSUE THREAD

**Issue by sergical** [Code-Forge-Net/Remix-Dev-Tools#56]
```
npm run dev

> sea-people-web@0.0.1 dev
> remix dev


 💿  remix dev

 info  building...
 info  built (4.6s)
Error: Dynamic require of "remix-development-tools" is not supported
    at file:///Users/sergiydybskiy/src/sea-people-web/build/index.js?t=1695932213829.837:11:9
    at file:///Users/sergiydybskiy/src/sea-people-web/build/index.js?t=1695932213829.837:1750:26
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

### root.tsx
```root.tsx
let AppExport = App;

if (ENVIRONMENT === 'development') {
  const { withDevTools } = require('remix-development-tools');
  AppExport = withDevTools(AppExport);
}

export default withSentry(AppExport);
```

Was working locally with `const { withDevTools } = await import("remix-development-tools"); ` but had to update to `require` for Vercel to build. 

```
"@remix-run/react": "2.0.1",
"remix-development-tools": "^3.0.3",
```

**Comment by AlemTuzlak** [comment]
I think the main culprit here is the `if(ENVIRONMENT)` check because esbuild doesn't probably strip out the if check in your production build, you can easily check this by building with the production flag and uploading your metafile in the /build folder to esbuild/analyze and see if remix dev tools are in the node modules

**Comment by sergical** [comment]
<img width="1497" alt="Screenshot 2023-09-29 at 3 18 22 PM" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/3760543/c1013898-ace5-4d68-bb48-14913a3c8eb9">

With 
```
let AppExport = App;

const { withDevTools } = await import('remix-development-tools');
AppExport = withDevTools(AppExport);

export default withSentry(AppExport);
```

Ran the `remix build --sourcemap` and uploaded the `metafile.server.json` to https://esbuild.github.io/analyze/

**Comment by AlemTuzlak** [comment]
You need to wrap the import and the addition to the export in an if check with process.env.NODE_ENV === "development" to make esbuuld not bundle it into your production build, check the README.md youcan literally copy/paste it and it will work, youcan also install it as a dependency but I don't recommend you do that because it's not meant to be bundled into production envs

**Comment by sergical** [comment]
How is it going to be different from what I posted in the original message? `ENVIRONMENT` is a `process.env` variable I set in my `.env` as well as an environment variable on Vercel

**Comment by AlemTuzlak** [comment]
I'm pretty sure that esbuild doesn't pick it up properly and still bundles your code, just try it out and see if it works I tested it on 5x different projects

**Comment by sergical** [comment]
```
let AppExport = App;

if (process.env.NODE_ENV === 'development') {
  const { withDevTools } = await import('remix-development-tools');
  AppExport = withDevTools(AppExport);
}

export default withSentry(AppExport);
```

Then I run 
```
npm run build

> sea-people-web@0.0.1 build
> NODE_ENV=production remix build --sourcemap

 info  building... (NODE_ENV=production)
 warn  🚨  source maps enabled in production
┃ You are using `--sourcemap` to enable source maps in production,
┃ making your server-side code publicly visible in the browser.
┃ This is highly discouraged!
┃ If you insist, ensure that you are using environment variables for secrets
┃ and are not hard-coding them in your source.
┗
 info  built (1.8s)
 ```

`metafile.server.json`

<img width="1680" alt="Screenshot 2023-09-29 at 3 38 37 PM" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/3760543/095933c6-e8ab-43e4-8af3-8a43df6f9cb6">

`metafile.json`

<img width="1680" alt="Screenshot 2023-09-29 at 3 42 53 PM" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/3760543/b9894796-5ffd-4b43-afa6-f6e642b16d5e">

Is this expected? for it to be on server and not on client?

I do really appreciate your help and sorry for not understanding this right away.

**Comment by sergical** [comment]
Getting the following in Vercel with the above code 

```
If you are installing esbuild with npm, make sure that you don't specify the
--
15:55:45.871 | "--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
15:55:45.871 | of "package.json" is used by esbuild to install the correct binary executable
15:55:45.871 | for your current platform.
15:55:45.888 | Error: Command "npm run build" exited with 1
```

**Comment by AlemTuzlak** [comment]
@sergical I assume you're using a custom server for vercel, you're probably missing the same if check there, it is more important to make sure your server doesn't have the import because the server uses a ws locally which doesn't work in many runtimes, make sure that you add NODE_ENV === "development" there too and you should be good to go!

**Comment by sergical** [comment]
just checked, everything built as expected, thank you so much! if you have a buy me a coffee link, please share! sorry once again

**Comment by AlemTuzlak** [comment]
@sergical no need to apologise my friend, all is good 👍 glad to be of service. I have ot on my profile, but you can find it here too: https://www.buymeacoffee.com/tzlak975
Enjoy the dev tools!
