### ISSUE TITLE
RDT increases HMR rebuild time

### ISSUE THREAD

**Issue by xHomu** [Code-Forge-Net/Remix-Dev-Tools#62]
RDT adds a decent overhead to the hmr rebuild atm, adding up to half second to a clean template on an older machine.

This is probably because the lucide dependency, here's a tree-map comparison with/without RDT installed:

<img width="1616" alt="image" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/84349818/a4d0a6e3-734d-417f-8b34-9280055944e2">
<img width="1616" alt="image" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/84349818/60bb9ebc-a6c9-4ae8-a6f0-cdc73f8df903">

We should able to at least treeshake out lucide by using @jacobparis' Sly https://sly-cli.fly.dev/

**Comment by AlemTuzlak** [comment]
@xHomu I've been wanting to move away from lucide for this exact reason for a big ass while now, even mentioned it in our discord chat a while back, I think this is a good time to do that

**Comment by xHomu** [comment]
Looks much better now!

![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/84349818/72c5eecc-6108-49da-88d5-906dc627983d)

**Comment by AlemTuzlak** [comment]
> Looks much better now!
> 
> ![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/84349818/72c5eecc-6108-49da-88d5-906dc627983d)
> 

You gotta show me where to see this so I can tree shake it more

**Comment by xHomu** [comment]
Run Lighthouse in Chrome devtools, there should be a treemap button underneath the web vital scores.

![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/84349818/4718fb67-d30d-4134-9cd7-59f1cb038d85)

To see the actual bundles in a production build, you need to use `remix run --sourcemap`.
