### ISSUE TITLE
Layout of RDT is somehow corrupted

### ISSUE THREAD

**Issue by msevestre** [Code-Forge-Net/Remix-Dev-Tools#63]
![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/1041237/ad73630f-7866-4068-af8e-a9a8d0b73193)
![image](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/1041237/7a75b8a7-da88-4d19-9d90-5355ef52e32d)

Suggestions. MAke sure icons do not overlap the text

**Comment by AlemTuzlak** [comment]
This is due to specific project css that overrides the css of the library, something like:
```jsx
  ol > li {
    @apply relative;
  }
```

**Comment by msevestre** [comment]
Shouldn't RDT be able to deal with this lol
