### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by arielvieira** [Code-Forge-Net/Remix-Dev-Tools#65]
When trying to run with the latest Cloudflare Pages adapter template the wrangler cli won't start due to the following error:
```js
service core:user:worker: Uncaught ReferenceError: global is not defined
  at oqu69tjsd1.js:57552:18 in singleton
  at oqu69tjsd1.js:57555:5 in node_modules/remix-development-tools/dist/index.cjs
  at oqu69tjsd1.js:82:50
  at oqu69tjsd1.js:62684:26
X [ERROR] MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
```

### Steps to reproduce
1. Start a new remix project using Cloudflare Pages adapter `npx create-remix --template remix-run/remix/templates/cloudflare-pages`
2. Install and [configure ](https://github.com/Code-Forge-Net/Remix-Dev-Tools#getting-started)RDT `yarn add remix-development-tools -D`
3. Start the project with `yarn dev`

### Environment information 
```
- node: 20.8.0
- yarn: 1.22.19
- remix: 2.1.0
- remix-development-tools: 3.2.2
- wrangler: 3.1.1
- windows: 11
```

### Possible Causes
Since wrangler run in another JavaScript runtime that is not node and since the `singleton` function uses the global object that is not available in the Cloudflare runtime so its throws an error.

https://github.com/Code-Forge-Net/Remix-Dev-Tools/blob/50d55572cde95f6514d0f1cccb184cc01575632c/src/dev-server/singleton.ts#L6

**Comment by AlemTuzlak** [comment]
@arielvieira Thank you so much for this report, the issue really is in the fact that RDT weren't made to run in serverless environments and the idea was to run them locally only, I plan to improve this for cloudflare by probably switching over to web standard apis instead of web sockets, also will need to figure something out for singletons as you pointed out. But this is not a straightforward process and I need to test a lot of stuff out. I am actively exploring bringing RDT to every environment without issues

**Comment by bgaleotti** [comment]
@AlemTuzlak I had the same issue while upgrading to [remix@2.2.0](https://github.com/remix-run/remix/releases/tag/remix%402.2.0) and using vite. I had to patch `global` with `globalThis` (same as the [remember](https://github.com/epicweb-dev/remember/blob/15f70d66c44a5b9b4ec74f5084b899f2e41b0e31/index.js#L13) lib) and everything is working ok. BTW, I'm not using Cloudflare runtime, just plain Node.js.

/cc @arielvieira

**Comment by AlemTuzlak** [comment]
I guess I will create a PR that resolves this issue separately, already fixed it on another PR so won't take long

**Comment by AlemTuzlak** [comment]
But this still won't resolve the issue with cloudflare
