### ISSUE TITLE
Not possible to change websocket port in client

### ISSUE THREAD

**Issue by keul** [Code-Forge-Net/Remix-Dev-Tools#66]
the `wsPort` parameter works as expected on my custom server, but it seems is not possible to change it on the client.

https://github.com/Code-Forge-Net/Remix-Dev-Tools/blob/50d55572cde95f6514d0f1cccb184cc01575632c/src/RemixDevTools/hooks/useDevServerConnection.ts#L52

Although the parameter _can_ be passed to `useDevServerConnection` its always called with no params, so default 8080 is used

**Comment by AlemTuzlak** [comment]
@keul I will be looking at this / fixing it very soon! Thank you for the report

**Comment by xHomu** [comment]
Last time I encountered this, turns out I was passing in the initial build without withServerDevTools. 

https://github.com/manawiki/core/commit/18f85565c0823085b54ddb19edaf28c78a7b3ae3#diff-81f1e1d9edc082e5508df8a7d86d802b361e59aa76c17abf37619e50fefcb134L139

**Comment by AlemTuzlak** [comment]
@keul I've tested it out yesterday, in order fori t to work you need to pass it into the config as the second parameter,
withDevTools(App, { wsPort: 5000 })

**Comment by keul** [comment]
I tried both this…

```ts
if (process.env.NODE_ENV === "development") {
  const { withDevTools } = await import("remix-development-tools");
  AppExport = withDevTools(AppExport, {
    wsPort: 9999,
  });
}

export default AppExport;
```

…and this…

```ts
if (process.env.NODE_ENV === "development") {
  const { defineClientConfig, withDevTools } = await import("remix-development-tools");
  const config = defineClientConfig({
    wsPort: 9999,
  });
  AppExport = withDevTools(AppExport, config);
}

export default AppExport;
```

But I still see it trying to call on ws://localhost:8080/

**Comment by keul** [comment]
Uhm, after upgrading to latest version (3.3.0, I was on 3.2.x) the behaviour changed a bit, but maybe now is more clear what is the problem.

I was confused by seeing failed connections to `localhost:8080`: is not my remix app, but an API rest endpoint I'm using from remix! Someway it's trying to connect to this address using websockets. If I disable RDT, these connections attempts disappears. 🤔

**Comment by AlemTuzlak** [comment]
Interesting, well the server part of rdt exposes a websocket to communicate with the client and the client uses this to fetch server timings etc. So you should be able to connect by changing the port number tp the same free port on both server and client, I'll be releasing a new version tomorrow that allows you to not connect at all

**Comment by keul** [comment]
I see both successful _and_ failing WS connections: on 9999 they succeed

![Screenshot 2023-10-23 alle 19 10 56](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/284924/3670c3bb-58a0-4226-b0d1-be46b373790f)

on 8080 (obviously) the fails…

![Screenshot 2023-10-23 alle 19 11 07](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/284924/7d64fade-7149-41fb-a336-f8751a2947e3)

**Comment by AlemTuzlak** [comment]
@keul I moved it to the settings page, merging the pr and releasing, you shouldn't have these problems anymore

**Comment by keul** [comment]
@AlemTuzlak I've to be honest, now I don't get anymore how to change the WS port on the client

**Comment by AlemTuzlak** [comment]
@keul go to settings tab on the client, enable swrver dev tools and change it (enabled by default)

**Comment by keul** [comment]
OK, not exactly convenient as every developer in the team should do this (on every browser), but it works now! 🙌

**Comment by AlemTuzlak** [comment]
> OK, not exactly convenient as every developer in the team should do this (on every browser), but it works now! 🙌 

Oh man that's a good point 🤔 I'll see if I can bring back the old approach + the new one

**Comment by TheRealFlyingCoder** [comment]
Just jumping in, had the same issue and given there's no documentation on it I didn't even think to check the UI settings for the port setting 🤷

I think setting your own port would be common enough to warrant a tiny section in the readme.

I think it should be a config passed to `withDevTools` for sure same as `withServerDevTools`... and then show up in the settings for you to change on the fly if you need to... although I don't understand why you'd ever want it to not match the wsPort?

**Comment by NicolasCharpentier** [comment]
I do confirm that that is not intuitive and having a param in the client side config would be more
