### ISSUE TITLE
Trying to use remix developement tools in blue stack

### ISSUE THREAD

**Issue by satelin2002** [Code-Forge-Net/Remix-Dev-Tools#71]
`import { cssBundleHref } from "@remix-run/css-bundle";
import type { LinksFunction, LoaderFunctionArgs } from "@remix-run/node";
import { json } from "@remix-run/node";
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from "@remix-run/react";
import rdtStylesheet from "remix-development-tools/index.css";

import { getUser } from "~/session.server";
import stylesheet from "~/tailwind.css";

export const links: LinksFunction = () => [
  { rel: "stylesheet", href: stylesheet },
  ...(cssBundleHref ? [{ rel: "stylesheet", href: cssBundleHref }] : []),
  ...(process.env.NODE_ENV === "development"
    ? [{ rel: "stylesheet", href: rdtStylesheet }]
    : []),
];

export const loader = async ({ request }: LoaderFunctionArgs) => {
  return json({ user: await getUser(request) });
};

function App() {
  return (
    <html lang="en" className="h-full">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <Meta />
        <Links />
      </head>
      <body className="h-full">
        <Outlet />
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
    </html>
  );
}

let AppExport = App;
if (process.env.NODE_ENV === "development") {
  const {
    withDevTools,
  } = async () => {
    await import("remix-development-tools");
  };
  AppExport = withDevTools(AppExport);
}

export default AppExport;
`

getting the following error

/Users/stelang/projects/remix/remix-app/app/root.tsx:55
  AppExport = withDevTools(AppExport);
              ^
TypeError: withDevTools is not a function
    at Object.<anonymous> (/Users/stelang/projects/remix/remix-app/app/root.tsx:55:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

**Comment by AlemTuzlak** [comment]
@satelin2002 this seems to be an issue with 
```tsx
const {
withDevTools,
} = async () => {
await import("remix-development-tools");
};
``` 
it should be
```tsx
const {
withDevTools,
} =   await import("remix-development-tools");
 
```
