### ISSUE TITLE
Form POST via conform for multiselect show only last item

### ISSUE THREAD

**Issue by lichtner** [Code-Forge-Net/Remix-Dev-Tools#74]
I use react-select with `isMulti` as multiselect

```
const schema = z.object({
  tags: z.string().array(),
})
...
export async function loader() {
  return json({ tags: db.tag.findMany({})})
}

export async function action() {
   ... 
  console.log(submission.value.tags)   
}

export default function Form() {
 return (
   ...
   <CreatableSelect name="tags" isMulti options={tags} />
   ...
  )
}
```

In function action `console.log(submission.value.tags)`  log `[ '1', '4', 'aaa' ]` 
but in RDT in Active page tab on right side show POST only last value for tags: `tags: string "aaa"`

**Comment by AlemTuzlak** [comment]
@lichtner This might be caused by the fact I use Object.fromEntries(formData.entries()) to get the form Data, I'll look into this
