### ISSUE TITLE
All Active page accordions collapse on revalidate data

### ISSUE THREAD

**Issue by okalil** [Code-Forge-Net/Remix-Dev-Tools#8]
If I open a route accordion inside Active page tab, calling useRevalidator().revalidate makes all accordions to collapse. 
That is bad because I have to open the accordion again to see the data I was looking.

**Comment by AlemTuzlak** [comment]
Considering I would have to persist stuff between renders I might just see if there is a way to add a way to see the difference between now/before

**Comment by okalil** [comment]
Why would you need to persist stuff? Keep accordion state open would be enough

**Comment by AlemTuzlak** [comment]
@okalil I meant persist in terms of using state to persist across renders, but I am wondering if it would be more useful to have like a red - before field and green - after like a diff on github
