### ISSUE TITLE
Killing server does not kill all node processes

### ISSUE THREAD

**Issue by aburkowsky9** [Code-Forge-Net/Remix-Dev-Tools#82]
Every time I kill the server with `ctrl + c` on mac my list of node processes grows by 1. I have confirmed this behavior stops when I remove the dev tools from my startup script. This happens regardless of the terminal i use (vscode integrated, warp, etc).

Version: `v3.4.0`
Startup Script: `"remix dev -c \"rdt-cjs-serve ./build/index.js\" --manual"`

<img width="856" alt="Screenshot 2023-12-06 at 11 48 08 AM" src="https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/38677277/dedca712-a01e-4b74-84b9-c704b09165cf">

**Comment by AlemTuzlak** [comment]
This is a known issue and already has been reported. I plan to deprecate this and remove the dev servers once vite is fully stabilized so I won't be fixing this due to that reason. Support for this will be fully dropped in the near future
