### ISSUE TITLE
Vite plugin breaks when exporting a `links` function

### ISSUE THREAD

**Issue by brookslybrand** [Code-Forge-Net/Remix-Dev-Tools#87]
For some reason when exporting a `links` function the dev tools plugin blows up 😬 

https://stackblitz.com/edit/remix-run-remix-qrkkuu?file=app%2Froot.tsx

**Comment by AlemTuzlak** [comment]
Interesting, this is new, I tested this scenario out and it was working before, I'll look into this, as a workaround until then you can export it as a const

**Comment by brookslybrand** [comment]
> Interesting, this is new, I tested this scenario out and it was working before, I'll look into this, as a workaround until then you can export it as a const

Weird, thanks for the work around! Glad to have pointed out the issue 🙂

**Comment by AlemTuzlak** [comment]
@brookslybrand fixed in 3.7.1, was a typo where i left `const` instead of `function` in the code, thank you for pointint it out!

**Comment by brookslybrand** [comment]
Awesome! Thanks @AlemTuzlak
