### ISSUE TITLE
process undefined in link

### ISSUE THREAD

**Issue by HananoshikaYomaru** [Code-Forge-Net/Remix-Dev-Tools#90]
![CleanShot 2024-01-11 at 16 58 39@2x](https://github.com/Code-Forge-Net/Remix-Dev-Tools/assets/43137033/024853e4-aef2-42f6-82b9-9d9d3056a9bc)

Sorry I don't quite understand here. When I put this in the app, it just throw error because process is undefined in client.

**Comment by HananoshikaYomaru** [comment]
No I am not using Vite. I am just using the normal remix starter. So there are not compatible?

**Comment by AlemTuzlak** [comment]
this could happen in remix vite starters but shouldn't in newer ones, what you can try to do is use import.meta.env and that should work fine I believe

**Comment by HananoshikaYomaru** [comment]
I found that my mistake is that I am not accessing `process.env.NODE_ENV` but a custom `process.env.PROJECT_ENV`. Turns out NODE_ENV is a exceptional case for remix that it can access this value even in the client side. Sorry to borther you, turns out is me not familiar with remix. ❤️ That's why I need the dev tools. Love your work. Thx.

**Comment by AlemTuzlak** [comment]
No worries glad you fixed it! Thank you 🙏
